### ISSUE TITLE
[TRACKER] repositories with missing configuration

### ISSUE THREAD

**Issue by gforcada** [plone/meta#75]
To ease the task of finding which repositories are still not being configured with `plone/meta` and maybe the explanation 
of why, here is an up-to-date list:

- [ ] [diazo](https://github.com/plone/diazo)
- [x] [plone.alterego](https://github.com/plone/plone.alterego): https://github.com/plone/plone.alterego/pull/7
- [x] [plone.app.caching](https://github.com/plone/plone.app.caching): https://github.com/plone/plone.app.caching/pull/120
- [ ] [plone.app.content](https://github.com/plone/plone.app.content): https://github.com/plone/plone.app.content/pull/262
- [x] [plone.app.contentrules](https://github.com/plone/plone.app.contentrules): https://github.com/plone/plone.app.contentrules/pull/82
- [x] [plone.app.customerize](https://github.com/plone/plone.app.customerize): https://github.com/plone/plone.app.customerize/pull/21
- [x] [plone.app.intid](https://github.com/plone/plone.app.intid): https://github.com/plone/plone.app.intid/pull/8
- [x] [plone.app.iterate](https://github.com/plone/plone.app.iterate): https://github.com/plone/plone.app.iterate/pull/106
- [x] [plone.app.layout](https://github.com/plone/plone.app.layout): https://github.com/plone/plone.app.layout/pull/334
- [x] [plone.app.multilingual](https://github.com/plone/plone.app.multilingual): https://github.com/plone/plone.app.multilingual/pull/415
- [x] [plone.app.redirector](https://github.com/plone/plone.app.redirector): https://github.com/plone/plone.app.redirector/pull/27
- [x] [plone.app.registry](https://github.com/plone/plone.app.registry): https://github.com/plone/plone.app.registry/pull/65
- [x] [plone.app.relationfield](https://github.com/plone/plone.app.relationfield): https://github.com/plone/plone.app.relationfield/pull/37
- [ ] [plone.app.robotframework](https://github.com/plone/plone.app.robotframework): https://github.com/plone/plone.app.robotframework/pull/145
- [x] [plone.app.testing](https://github.com/plone/plone.app.testing): https://github.com/plone/plone.app.testing/pull/82
- [ ] [plone.app.upgrade](https://github.com/plone/plone.app.upgrade)
- [x] [plone.app.users](https://github.com/plone/plone.app.users): https://github.com/plone/plone.app.users/pull/117
- [x] [plone.behavior](https://github.com/plone/plone.behavior): https://github.com/plone/plone.behavior/pull/24
- [x] [plone.caching](https://github.com/plone/plone.caching): https://github.com/plone/plone.caching/pull/9
- [x] [plone.contentrules](https://github.com/plone/plone.contentrules): https://github.com/plone/plone.contentrules/pull/13
- [x] [plone.event](https://github.com/plone/plone.event): https://github.com/plone/plone.event/pull/16
- [x] [plone.folder](https://github.com/plone/plone.folder): https://github.com/plone/plone.folder/pull/18
- [ ] [plone.formwidget.namedfile](https://github.com/plone/plone.formwidget.namedfile): https://github.com/plone/plone.formwidget.namedfile/pull/61
- [x] [plone.indexer](https://github.com/plone/plone.indexer): https://github.com/plone/plone.indexer/pull/9
- [x] [plone.intelligenttext](https://github.com/plone/plone.intelligenttext): https://github.com/plone/plone.intelligenttext/pull/10
- [x] [plone.keyring](https://github.com/plone/plone.keyring): https://github.com/plone/plone.keyring/pull/9
- [x] [plone.locking](https://github.com/plone/plone.locking): https://github.com/plone/plone.locking/pull/21
- [ ] [plone.namedfile](https://github.com/plone/plone.namedfile)
- [x] [plone.protect](https://github.com/plone/plone.protect): https://github.com/plone/plone.protect/pull/100
- [x] [plone.registry](https://github.com/plone/plone.registry): https://github.com/plone/plone.registry/pull/26
- [x] [plone.resourceeditor](https://github.com/plone/plone.resourceeditor): https://github.com/plone/plone.resourceeditor/pull/31
- [x] [plone.resource](https://github.com/plone/plone.resource): https://github.com/plone/plone.resource/pull/33
- [ ] [plone.restapi](https://github.com/plone/plone.restapi)
- [x] [plone.rfc822](https://github.com/plone/plone.rfc822): https://github.com/plone/plone.rfc822/pull/9
- [x] [plone.staticresources](https://github.com/plone/plone.staticresources): https://github.com/plone/plone.staticresources/pull/279
- [ ] [plone.testing](https://github.com/plone/plone.testing): https://github.com/plone/plone.testing/pull/82
- [ ] [plone.volto](https://github.com/plone/plone.volto)
- [x] [plonetheme.barceloneta](https://github.com/plone/plonetheme.barceloneta): https://github.com/plone/plonetheme.barceloneta/pull/327
- [x] [plone.theme](https://github.com/plone/plone.theme): https://github.com/plone/plone.theme/pull/9
- [x] [plone.transformchain](https://github.com/plone/plone.transformchain): https://github.com/plone/plone.transformchain/pull/12
- [x] [plone.uuid](https://github.com/plone/plone.uuid): https://github.com/plone/plone.uuid/pull/7
- [x] [Products.CMFDiffTool](https://github.com/plone/Products.CMFDiffTool): https://github.com/plone/Products.CMFDiffTool/pull/43
- [x] [Products.CMFDynamicViewFTI](https://github.com/plone/Products.CMFDynamicViewFTI): https://github.com/plone/Products.CMFDynamicViewFTI/pull/24
- [x] [Products.CMFEditions](https://github.com/plone/Products.CMFEditions): https://github.com/plone/Products.CMFEditions/pull/96
- [x] [Products.CMFPlone](https://github.com/plone/Products.CMFPlone): https://github.com/plone/Products.CMFPlone/pull/3777
- [ ] [Products.CMFPlacefulWorkflow](https://github.com/plone/Products.CMFPlacefulWorkflow)
- [ ] [Products.DateRecurringIndex](https://github.com/collective/Products.DateRecurringIndex)
- [x] [Products.isurlinportal](https://github.com/plone/Products.isurlinportal): https://github.com/plone/Products.isurlinportal/pull/11
- [x] [Products.MimetypesRegistry](https://github.com/plone/Products.MimetypesRegistry): https://github.com/plone/Products.MimetypesRegistry/pull/22
- [ ] [Products.PortalTransforms](https://github.com/plone/Products.PortalTransforms): https://github.com/plone/Products.PortalTransforms/pull/55
- [ ] [Products.statusmessages](https://github.com/plone/Products.statusmessages)
- [x] [Products.validation](https://github.com/plone/Products.validation): https://github.com/plone/Products.validation/issues/9

## Ecosystem, not urgent

Mosaic:
- [plone.app.blocks](https://github.com/plone/plone.app.blocks)
- [plone.app.drafts](https://github.com/plone/plone.app.drafts)
- [plone.app.mosaic](https://github.com/plone/plone.app.mosaic)
- [plone.app.standardtiles](https://github.com/plone/plone.app.standardtiles)
- [plone.app.tiles](https://github.com/plone/plone.app.tiles)
- [plone.tiles](https://github.com/plone/plone.tiles)
- [Products.ExtendedPathIndex](https://github.com/plone/Products.ExtendedPathIndex)

## 🤔 __Do they need it?__

- [diazo](https://github.com/plone/diazo)
- [collective.monkeypatcher](https://github.com/plone/collective.monkeypatcher)
- [collective.recipe.omelette](https://github.com/collective/collective.recipe.omelette)
- [collective.xmltestreport](https://github.com/collective/collective.xmltestreport)
- [i18ndude](https://github.com/collective/i18ndude)
- [icalendar](https://github.com/collective/icalendar)
- [mockup](https://github.com/plone/mockup)
- [Plone](https://github.com/plone/Plone)
- [plone.api](https://github.com/plone/plone.api)
- [plone.app.locales](https://github.com/collective/plone.app.locales)
- [plone.app.lockingbehavior](https://github.com/plone/plone.app.lockingbehavior)
- [plone.app.upgrade](https://github.com/plone/plone.app.upgrade)
- [plone.app.widgets](https://github.com/plone/plone.app.widgets)
- [plone.recipe.alltests](https://github.com/plone/plone.recipe.alltests)
- [plone.recipe.precompiler](https://github.com/plone/plone.recipe.precompiler)
- [plone.recipe.zeoserver](https://github.com/plone/plone.recipe.zeoserver)
- [plone.recipe.zope2instance](https://github.com/plone/plone.recipe.zope2instance)
- [plone.reload](https://github.com/plone/plone.reload)
- [plone.restapi](https://github.com/plone/plone.restapi)
- [plone.themepreview](https://github.com/plone/plone.themepreview)
- [plone.volto](https://github.com/plone/plone.volto)
- [repoze.xmliter](https://github.com/repoze/repoze.xmliter)
- [robotsuite](https://github.com/collective/robotsuite)
- [zodbverify](https://github.com/plone/zodbverify)

**Comment by jensens** [comment]
`plone.tiles` is part of the Mosaic ecosystem, which is a kind of official add-on.
Should we add the other Mosaic packages too?

**Comment by gforcada** [comment]
if they are ecosystem and not core, I would say that is nice to have, but not _required_. First we need to solve the circular dependencies and keep clustering the packages (and their logic/functionality) together, and then the ecosystem can follow along...

**Comment by jensens** [comment]
> this is core and should be covered (IMO):

I added those to the above list, except for `plone.app.widgets`, which goes into deprecation mode anyway.

**Comment by gforcada** [comment]
Though still are pending, I think we can go case by case now, and add/fix the missing packages.
